service: impact-register
runtime: nodejs10

handlers:
- url: /
  secure: always
  static_files: build/index.html
  upload: build/index.html
  http_headers:
    Access-Control-Allow-Origin: SAMEORIGIN
    X-Frame-Options: DENY
    X-Content-Type-Options: nosniff

- url: /(.*)
  secure: always
  static_files: build/\1
  upload: build/(.*)