
export const NEW_SPECIALITY = {
    "CARDIOLOGIST": ["Cardiology"],
    "CLINICAL CARDIOLOGIST": ["Cardiology"],
    "ECHO CARDIOLOGIST": ["Cardiology"],
    "PEAD CARDIOLOGIST": ["Cardiology"],
    "PRACTICING CARDIOLOGIST": ["Cardiology"],
    "INTERVENTIONAL CARDIOLOGIST": ["Cardiology"],
    "MBBS CARDIOLOGIST D CARD": ["Cardiology"],
    "MBBS DIABETOLOGIST D DIAB": ["Diabetology"],
    "CTV SURGEON": ["Surgery"],
    "CVTS": ["Cardiology"],
    "ELECTROPHYSIOLOGIST": ["General Medicine"],
    "CHEST PHYSICIAN": ["Cardiology"],
    "PULMONOLOGIST": ["Respiratory Medicine"],
    "DIABETOLOGIST": ["Diabetology"],
    "PRACTICING DIABETOLOGIST": ["Diabetology"],
    "ENDOCRINOLOGIST": ["Diabetology"],
    "GASTRO SURGEON": ["Gastroenterology & Hepatology", "Surgery"],
    "GASTROENTEROLOGIST": ["Gastroenterology & Hepatology"],
    "DENTIST": ["Dentistry"],
    "DERMATOLOGIST": ["Dermatology"],
    "COSMETIC DERMATOLOGIST": ["Dermatology"],
    "COSMETIC SURGEON": ["Dermatology"],
    "PAEDIATRIC DERMATOLOGIST": ["Dermatology", "Surgery"],
    "PLASTIC SURGEON": ["Dermatology", "Pediatrics"],
    "HAIR TRANSPLANT SURGEON": ["Dermatology", "Surgery"],
    "TRICHOLOGIST": ["Dermatology"],
    "OPHTHALMOLOGIST": ["Ophthalmology"],
    "OPTH CATARACT": ["Ophthalmology"],
    "OPTHAL CORNEA": ["Ophthalmology"],
    "OPTHAL GLAUCOMA": ["Ophthalmology"],
    "OPTHAL PHACO": ["Ophthalmology"],
    "OPTHAL RETINA": ["Ophthalmology"],
    "OPTOMETRIST": ["Ophthalmology"],
    "ORTHOPEDICIAN": ["Musculoskeletal Diseases"],
    "ORTHO SURGEON": ["Musculoskeletal Diseases"],
    "GYNAECOLOGIST": ["Obstetrics & Gynaecology"],
    "HAEMATOLOGIST": ["Obstetrics & Gynaecology"],
    "IVF": ["Obstetrics & Gynaecology"],
    "EMBRYOLOGIST": ["Obstetrics & Gynaecology"],
    "NEUROSURGEON": ["Neuropsychiatry", "Surgery"],
    "NEUROLOGIST": ["Neuropsychiatry"],
    "PAED NEUROLOGIST": ["Neuropsychiatry", "Pediatrics"],
    "PSYCHIATRIST": ["Neuropsychiatry"],
    "ID SPECIALIST": ["Infectious Diseases"],
    "INTENSIVE CARE": ["Critical Care Medicine"],
    "PRACTICING ICU CCU": ["Critical Care Medicine"],
    "PAEDIATRICIAN": ["Pediatrics"],
    "NEONATOLOGIST": ["Pediatrics"],
    "ONCOLOGIST": ["Oncology"],
    "RADIATION ONCOLOGIST": ["Oncology"],
    "RHEUMATOLOGIST": ["Musculoskeletal Diseases"],
    "NEPHROLOGIST": ["General Medicine"],
    "SURGEON": ["Surgery"],
    "PAEDIATRIC SURGEON": ["Surgery", "Pediatrics"],
    "ENT SURGEON": ["ENT", "Surgery"],
    "URO ONCOLOGIST": ["Oncology", "Urology"],
    "UROLOGIST": ["Urology"],
    "VASCULAR SURGEON": ["Surgery"],
    "MICROBIOLOGIST": ["Infectious Diseases"],
    "GENERAL PHYSICIAN": ["General Medicine"],
    "CONSULTANT PHYSICIAN": ["General Medicine"],
    "GP NON MBBS": ["General Medicine"],
    "ANAESTHETIST": ["General Medicine"],
    "NON MBBS": ["General Medicine"],
    "PURCHASE PHARMACY": ["General Medicine"],
    "OTHERS": ["General Medicine"],
};