export const UPDATE_USER_STAUS = 'updateUserStatus'
export const SEND_OTP_CLOUDFUNCTION = 'sendOTP'
export const VERIFY_OTP_COLUDFUNCTION = 'verifyOTP'
export const RETRY_OTP_CLOUDFUNCTION = 'resendOTP'
export const UPDATE_MOBILENUMBER_CLOUDFUNCTION = 'updateMobileNumber'