export const VIDEO_COLLECTION = 'videos'
export const EVENT_COLLECTION = 'events'
export const TIMELINE_COLLECTION = 'timeline'
export const LIKES_COLLECTION = 'likes'
export const SPEAKERS_COLLECTION = 'speakers'
export const QNA_COLLECTION = 'qna'