export const SPEAKERDATA_COOKIES = 'speakerData'
export const EVENTDATA_COOKIES = 'eventData'
export const TIMELINEDATA_COOKIES = 'timelineData'
export const VIDEODATA_COOKIES = 'videoData'
export const TRENDINGDATA_COOKIES = 'trendingData'
export const PARTNERWITHUS_COOKIES = 'partnerWithUs'
export const PARTNERWITHUSAGREE_COOKIES = 'partnerWithUsAgree'
