export const REGISTER_ROUTE = '/register'
export const LOGIN_ROUTE = '/login'
export const HOME_ROUTE = '/home'
export const TOPIC_ROUTE = '/topics'
export const EVENT_ROUTE = '/event'
export const RootRoute = '/'